name = "jsonify"
compatibility_date = "2024-10-19"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "jsonify"
database_id = "e7f5012c-e3f0-4b4e-891b-ecd018874f38"
migrations_dir = "drizzle/migrations"